include $(GNUSTEP_MAKEFILES)/common.make

TOOL_NAME = FizzBuzz
FizzBuzz_OBJCFLAGS = -std=c99
FizzBuzz_HEADERS =
FizzBuzz_OBJC_FILES = main.m
FizzBuzz_RESOURCE_FILES =

include $(GNUSTEP_MAKEFILES)/tool.make
