#!/usr/bin/env perl

=head1 DESCRIPTION

Players generally sit in a circle. The player designated to go first says the
number "1", and each player thenceforth counts one number in turn. However, any
number divisible by 'A' e.g. three is replaced by the word fizz and any
divisible by 'B' e.g. five by the word buzz. Numbers divisible by both become
fizz buzz. A player who hesitates or makes a mistake is either eliminated.

Write a program that prints out the the pattern generated by such a scenario
given the values of 'A'/'B' and 'N' which are read from an input text file. The
input text file contains three space delimited numbers i.e. A, B, N. The
program should then print out the final series of numbers using 'F' for fizz,
'B' for 'buzz' and 'FB' for fizz buzz.

=cut

use strict;
use warnings;

while (<DATA>) {
	chomp;
	fb( split /\s+/ );
}

sub fb {
	my ( $f, $b, $n ) = @_;
	my @results;
	foreach my $i ( 1 .. $n ) {
		my $out = $i;
		if ( $i % $f == 0 ) {
			$out = 'F';
		}
		if ( $i % $b == 0 ) {
			$out = $out eq 'F' ? 'FB' : 'B';
		}
		push @results, $out;
	}
	print join( ' ', @results ), "\n";
}

exit(0);

__DATA__
3 5 10
2 7 15
